In [1]:
import pandas as pd
import os


# read the clipboard and skip the first 2 rows

dfBasic = pd.read_clipboard(skiprows=2, header=None, sep=',')

dfBasic

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,1,Aaron Ekblad,18,FLA,D,81,14,0.15,0.33,0.48,...,50.6,9.7,3.5,5.0,8.5,1,0.0,1.0,0.0,ekblaaa01
1,2,Aaron Volpatti,29,WSH,LW,2,0,0.00,0.00,0.00,...,0.3,0.3,-0.1,0.0,0.0,0,NaN,NaN,NaN,volpaaa01
2,3,Adam Burish,32,SJS,RW,20,1,0.05,0.10,0.15,...,10.3,-6.3,-0.2,0.0,-0.2,0,NaN,NaN,NaN,burisad01
3,4,Adam Clendening,22,TOT,D,21,1,0.05,0.14,0.19,...,14.1,-1.8,0.1,0.9,1.0,0,NaN,NaN,NaN,clendad01
4,5,Adam Cracknell,29,CBJ,RW,17,0,0.00,0.06,0.06,...,8.0,-5.3,-0.4,-0.2,-0.5,0,NaN,NaN,NaN,crackad01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
969,970,Zack Kassian,24,VAN,RW,42,7,0.24,0.14,0.38,...,23.6,-3.7,1.5,0.3,1.8,0,NaN,NaN,NaN,kassiza01
970,971,Zack Smith,26,OTT,C,37,1,0.05,0.03,0.08,...,14.7,-1.9,-0.7,0.1,-0.6,0,NaN,NaN,NaN,smithza01
971,972,Zbyněk Michálek,32,TOT,D,68,4,0.06,0.12,0.18,...,41.1,0.6,0.0,3.4,3.4,0,NaN,NaN,NaN,michazb01
972,973,Zdeno Chára,37,BOS,D,63,8,0.13,0.19,0.32,...,39.2,8.2,1.3,3.2,4.5,1,0.0,1.0,0.0,charazd01
973,974,Zemgus Girgensons,21,BUF,C,61,12,0.25,0.25,0.49,...,47.0,-16.2,1.8,0.8,2.6,8,2.0,6.0,25.0,girgeze01

In [2]:
# add the custom headers
# Given text string
header_text = "Rk	Player	Age	Tm	Pos	GP	GoalsCreated	GPerGame	APerGame	PtsPerGame	GoalsCreatedPerGame	PIM	SOGPerGameAdjusted	GAdjusted	AAdjusted	PtsAdjusted	GCAdjusted	TotGF	TotPPGF	TotGA	TotPPGA	PlusMin	XGF	XGA	XPlusMin	OPS	DPS	TotPS	ShootOutAtt	ShootoutMade	ShootoutMiss	ShootOutPerc	UID"

# Split the text string into a list of headers
headers = header_text.split()

dfBasic.columns = headers

dfBasic

,Rk,Player,Age,Tm,Pos,GP,GoalsCreated,GPerGame,APerGame,PtsPerGame,...,XGA,XPlusMin,OPS,DPS,TotPS,ShootOutAtt,ShootoutMade,ShootoutMiss,ShootOutPerc,UID
0,1,Aaron Ekblad,18,FLA,D,81,14,0.15,0.33,0.48,...,50.6,9.7,3.5,5.0,8.5,1,0.0,1.0,0.0,ekblaaa01
1,2,Aaron Volpatti,29,WSH,LW,2,0,0.00,0.00,0.00,...,0.3,0.3,-0.1,0.0,0.0,0,NaN,NaN,NaN,volpaaa01
2,3,Adam Burish,32,SJS,RW,20,1,0.05,0.10,0.15,...,10.3,-6.3,-0.2,0.0,-0.2,0,NaN,NaN,NaN,burisad01
3,4,Adam Clendening,22,TOT,D,21,1,0.05,0.14,0.19,...,14.1,-1.8,0.1,0.9,1.0,0,NaN,NaN,NaN,clendad01
4,5,Adam Cracknell,29,CBJ,RW,17,0,0.00,0.06,0.06,...,8.0,-5.3,-0.4,-0.2,-0.5,0,NaN,NaN,NaN,crackad01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
969,970,Zack Kassian,24,VAN,RW,42,7,0.24,0.14,0.38,...,23.6,-3.7,1.5,0.3,1.8,0,NaN,NaN,NaN,kassiza01
970,971,Zack Smith,26,OTT,C,37,1,0.05,0.03,0.08,...,14.7,-1.9,-0.7,0.1,-0.6,0,NaN,NaN,NaN,smithza01
971,972,Zbyněk Michálek,32,TOT,D,68,4,0.06,0.12,0.18,...,41.1,0.6,0.0,3.4,3.4,0,NaN,NaN,NaN,michazb01
972,973,Zdeno Chára,37,BOS,D,63,8,0.13,0.19,0.32,...,39.2,8.2,1.3,3.2,4.5,1,0.0,1.0,0.0,charazd01
973,974,Zemgus Girgensons,21,BUF,C,61,12,0.25,0.25,0.49,...,47.0,-16.2,1.8,0.8,2.6,8,2.0,6.0,25.0,girgeze01

In [3]:
# Add the Season Field and remove goalies

# Add a new column "season" with the value season name

# Prompt the user for the "season" value
season_value = input("Enter the season value (e.g., '22-23'): ")

# Add a new column "season" with the user-inputted value
dfBasic["season"] = season_value

# Remove rows where "Pos" is equal to "G"
dfBasic = dfBasic[dfBasic["Pos"] != "G"]

dfBasic

,Rk,Player,Age,Tm,Pos,GP,GoalsCreated,GPerGame,APerGame,PtsPerGame,...,XPlusMin,OPS,DPS,TotPS,ShootOutAtt,ShootoutMade,ShootoutMiss,ShootOutPerc,UID,season
0,1,Aaron Ekblad,18,FLA,D,81,14,0.15,0.33,0.48,...,9.7,3.5,5.0,8.5,1,0.0,1.0,0.0,ekblaaa01,14-15
1,2,Aaron Volpatti,29,WSH,LW,2,0,0.00,0.00,0.00,...,0.3,-0.1,0.0,0.0,0,NaN,NaN,NaN,volpaaa01,14-15
2,3,Adam Burish,32,SJS,RW,20,1,0.05,0.10,0.15,...,-6.3,-0.2,0.0,-0.2,0,NaN,NaN,NaN,burisad01,14-15
3,4,Adam Clendening,22,TOT,D,21,1,0.05,0.14,0.19,...,-1.8,0.1,0.9,1.0,0,NaN,NaN,NaN,clendad01,14-15
4,5,Adam Cracknell,29,CBJ,RW,17,0,0.00,0.06,0.06,...,-5.3,-0.4,-0.2,-0.5,0,NaN,NaN,NaN,crackad01,14-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
969,970,Zack Kassian,24,VAN,RW,42,7,0.24,0.14,0.38,...,-3.7,1.5,0.3,1.8,0,NaN,NaN,NaN,kassiza01,14-15
970,971,Zack Smith,26,OTT,C,37,1,0.05,0.03,0.08,...,-1.9,-0.7,0.1,-0.6,0,NaN,NaN,NaN,smithza01,14-15
971,972,Zbyněk Michálek,32,TOT,D,68,4,0.06,0.12,0.18,...,0.6,0.0,3.4,3.4,0,NaN,NaN,NaN,michazb01,14-15
972,973,Zdeno Chára,37,BOS,D,63,8,0.13,0.19,0.32,...,8.2,1.3,3.2,4.5,1,0.0,1.0,0.0,charazd01,14-15
973,974,Zemgus Girgensons,21,BUF,C,61,12,0.25,0.25,0.49,...,-16.2,1.8,0.8,2.6,8,2.0,6.0,25.0,girgeze01,14-15

In [4]:
# Drop the columns
# Drop specified columns
columns_to_drop = ["Rk", "Player", "Age", "Tm", "GP", "PIM", "ShootOutAtt", "ShootoutMade", "ShoutoutMiss", "ShootOutPerc"]
dfBasic.drop(columns_to_drop, axis=1, errors='ignore', inplace=True)

dfBasic

/var/folders/7b/vdj0v45x3xsdh46qyk8w3h5h0000gn/T/ipykernel_62093/3877289701.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfBasic.drop(columns_to_drop, axis=1, errors='ignore', inplace=True)

,Pos,GoalsCreated,GPerGame,APerGame,PtsPerGame,GoalsCreatedPerGame,SOGPerGameAdjusted,GAdjusted,AAdjusted,PtsAdjusted,...,PlusMin,XGF,XGA,XPlusMin,OPS,DPS,TotPS,ShootoutMiss,UID,season
0,D,14,0.15,0.33,0.48,0.17,2.10,14,29,43,...,12,60.3,50.6,9.7,3.5,5.0,8.5,1.0,ekblaaa01,14-15
1,LW,0,0.00,0.00,0.00,0.00,0.50,0,0,0,...,0,0.6,0.3,0.3,-0.1,0.0,0.0,NaN,volpaaa01,14-15
2,RW,1,0.05,0.10,0.15,0.05,1.10,1,2,3,...,-6,4.0,10.3,-6.3,-0.2,0.0,-0.2,NaN,burisad01,14-15
3,D,1,0.05,0.14,0.19,0.06,0.81,1,3,4,...,2,12.2,14.1,-1.8,0.1,0.9,1.0,NaN,clendad01,14-15
4,RW,0,0.00,0.06,0.06,0.02,1.00,0,1,1,...,-8,2.8,8.0,-5.3,-0.4,-0.2,-0.5,NaN,crackad01,14-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
969,RW,7,0.24,0.14,0.38,0.17,1.31,11,7,18,...,-5,19.9,23.6,-3.7,1.5,0.3,1.8,NaN,kassiza01,14-15
970,C,1,0.05,0.03,0.08,0.04,1.03,2,1,3,...,-8,12.8,14.7,-1.9,-0.7,0.1,-0.6,NaN,smithza01,14-15
971,D,4,0.06,0.12,0.18,0.06,1.26,4,9,13,...,-3,41.8,41.1,0.6,0.0,3.4,3.4,NaN,michazb01,14-15
972,D,8,0.13,0.19,0.32,0.12,2.19,9,13,22,...,0,47.4,39.2,8.2,1.3,3.2,4.5,1.0,charazd01,14-15
973,C,12,0.25,0.25,0.49,0.20,1.89,17,16,33,...,-16,30.8,47.0,-16.2,1.8,0.8,2.6,6.0,girgeze01,14-15

In [5]:
# Construct the output file path
output_folder = "HockeyRef_Data_Files"
output_file_path = os.path.join(output_folder, f'{season_value}_MiscData.csv')

# Save the DataFrame to a CSV file with the constructed path
dfBasic.to_csv(output_file_path, index=False)