In [1]:
import pandas as pd
import os


# read the clipboard and skip the first 2 rows

dfBasic = pd.read_clipboard(skiprows=2, header=None, sep=',')

dfBasic

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,1,A.J. Greer,BOS,LW,0:29,61,NaN,8:58,-3.4,2.4,...,0:04,-37.2,14.3,0.0,NaN,0:03,15.1,0.0,0.0,greeraj01
1,2,Aaron Ekblad,FLA,D,0:45,71,NaN,17:18,1.5,3.1,...,3:17,1.1,9.8,1.0,NaN,2:47,-2.5,0.9,8.8,ekblaaa01
2,3,Aatu Räty,TOT,C,0:46,15,NaN,7:55,-2.5,1.2,...,0:27,19.8,0.0,0.0,NaN,0:00,NaN,NaN,NaN,ratyaa01
3,4,Adam Beckman,MIN,LW,0:48,9,NaN,9:58,7.0,0.0,...,0:43,-5.2,0.0,0.0,NaN,0:00,NaN,NaN,NaN,beckmad01
4,5,Adam Boqvist,CBJ,D,0:41,46,NaN,15:32,4.6,3.2,...,3:03,-1.9,6.0,1.3,NaN,0:02,31.5,0.0,0.0,boqviad01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946,947,Zach Whitecloud,VEG,D,0:44,59,NaN,15:43,-3.7,2.7,...,0:00,-20.9,0.0,0.0,NaN,1:22,-0.1,0.7,8.2,whiteza01
947,948,Zachary Jones,NYR,D,0:56,16,NaN,14:37,-10.6,2.1,...,0:53,-28.9,0.0,0.0,NaN,0:05,-16.4,0.0,0.0,jonesza01
948,949,Zack Kassian,ARI,RW,0:39,51,NaN,9:08,-6.8,0.8,...,0:00,NaN,0.0,0.0,NaN,0:01,-8.2,0.0,60.0,kassiza01
949,950,Zack MacEwen,TOT,C,0:44,56,NaN,10:59,-3.3,1.5,...,0:33,15.3,0.0,0.0,NaN,0:01,-9.5,NaN,NaN,macewza01
950,951,Zemgus Girgensons,BUF,C,0:41,80,NaN,11:27,-0.4,1.7,...,0:03,-1.6,11.2,0.0,NaN,1:27,-4.3,0.0,8.7,girgeze01

In [2]:
# add the custom headers
# Given text string
header_text = "Rk	Player	Age	Tm	ShiftLength	GP	Blank1	ATOI	CorsiForRelES	GFPer60	GAPer60	Blank2	ATOIPP	PPCorsiPercRel	PPGFPer60	PPGAPer60	Blank3	ATOISH	CorsiForRelSH	SHFPPer60	SHGAPer60	UID"

# Split the text string into a list of headers
headers = header_text.split()

dfBasic.columns = headers

dfBasic

,Rk,Player,Age,Tm,ShiftLength,GP,Blank1,ATOI,CorsiForRelES,GFPer60,...,ATOIPP,PPCorsiPercRel,PPGFPer60,PPGAPer60,Blank3,ATOISH,CorsiForRelSH,SHFPPer60,SHGAPer60,UID
0,1,A.J. Greer,BOS,LW,0:29,61,NaN,8:58,-3.4,2.4,...,0:04,-37.2,14.3,0.0,NaN,0:03,15.1,0.0,0.0,greeraj01
1,2,Aaron Ekblad,FLA,D,0:45,71,NaN,17:18,1.5,3.1,...,3:17,1.1,9.8,1.0,NaN,2:47,-2.5,0.9,8.8,ekblaaa01
2,3,Aatu Räty,TOT,C,0:46,15,NaN,7:55,-2.5,1.2,...,0:27,19.8,0.0,0.0,NaN,0:00,NaN,NaN,NaN,ratyaa01
3,4,Adam Beckman,MIN,LW,0:48,9,NaN,9:58,7.0,0.0,...,0:43,-5.2,0.0,0.0,NaN,0:00,NaN,NaN,NaN,beckmad01
4,5,Adam Boqvist,CBJ,D,0:41,46,NaN,15:32,4.6,3.2,...,3:03,-1.9,6.0,1.3,NaN,0:02,31.5,0.0,0.0,boqviad01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946,947,Zach Whitecloud,VEG,D,0:44,59,NaN,15:43,-3.7,2.7,...,0:00,-20.9,0.0,0.0,NaN,1:22,-0.1,0.7,8.2,whiteza01
947,948,Zachary Jones,NYR,D,0:56,16,NaN,14:37,-10.6,2.1,...,0:53,-28.9,0.0,0.0,NaN,0:05,-16.4,0.0,0.0,jonesza01
948,949,Zack Kassian,ARI,RW,0:39,51,NaN,9:08,-6.8,0.8,...,0:00,NaN,0.0,0.0,NaN,0:01,-8.2,0.0,60.0,kassiza01
949,950,Zack MacEwen,TOT,C,0:44,56,NaN,10:59,-3.3,1.5,...,0:33,15.3,0.0,0.0,NaN,0:01,-9.5,NaN,NaN,macewza01
950,951,Zemgus Girgensons,BUF,C,0:41,80,NaN,11:27,-0.4,1.7,...,0:03,-1.6,11.2,0.0,NaN,1:27,-4.3,0.0,8.7,girgeze01

In [3]:
# Add the Season Field

# Add a new column "season" with the value season name

# Prompt the user for the "season" value
season_value = input("Enter the season value (e.g., '22-23'): ")

# Add a new column "season" with the user-inputted value
dfBasic["season"] = season_value

dfBasic

,Rk,Player,Age,Tm,ShiftLength,GP,Blank1,ATOI,CorsiForRelES,GFPer60,...,PPCorsiPercRel,PPGFPer60,PPGAPer60,Blank3,ATOISH,CorsiForRelSH,SHFPPer60,SHGAPer60,UID,season
0,1,A.J. Greer,BOS,LW,0:29,61,NaN,8:58,-3.4,2.4,...,-37.2,14.3,0.0,NaN,0:03,15.1,0.0,0.0,greeraj01,22-23
1,2,Aaron Ekblad,FLA,D,0:45,71,NaN,17:18,1.5,3.1,...,1.1,9.8,1.0,NaN,2:47,-2.5,0.9,8.8,ekblaaa01,22-23
2,3,Aatu Räty,TOT,C,0:46,15,NaN,7:55,-2.5,1.2,...,19.8,0.0,0.0,NaN,0:00,NaN,NaN,NaN,ratyaa01,22-23
3,4,Adam Beckman,MIN,LW,0:48,9,NaN,9:58,7.0,0.0,...,-5.2,0.0,0.0,NaN,0:00,NaN,NaN,NaN,beckmad01,22-23
4,5,Adam Boqvist,CBJ,D,0:41,46,NaN,15:32,4.6,3.2,...,-1.9,6.0,1.3,NaN,0:02,31.5,0.0,0.0,boqviad01,22-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946,947,Zach Whitecloud,VEG,D,0:44,59,NaN,15:43,-3.7,2.7,...,-20.9,0.0,0.0,NaN,1:22,-0.1,0.7,8.2,whiteza01,22-23
947,948,Zachary Jones,NYR,D,0:56,16,NaN,14:37,-10.6,2.1,...,-28.9,0.0,0.0,NaN,0:05,-16.4,0.0,0.0,jonesza01,22-23
948,949,Zack Kassian,ARI,RW,0:39,51,NaN,9:08,-6.8,0.8,...,NaN,0.0,0.0,NaN,0:01,-8.2,0.0,60.0,kassiza01,22-23
949,950,Zack MacEwen,TOT,C,0:44,56,NaN,10:59,-3.3,1.5,...,15.3,0.0,0.0,NaN,0:01,-9.5,NaN,NaN,macewza01,22-23
950,951,Zemgus Girgensons,BUF,C,0:41,80,NaN,11:27,-0.4,1.7,...,-1.6,11.2,0.0,NaN,1:27,-4.3,0.0,8.7,girgeze01,22-23

In [4]:
# Drop the columns
# Drop specified columns
columns_to_drop = ["Rk", "Player", "Age", "Tm", "GP", "Blank1", "ATOI", "Blank2", "Blank3"]
dfBasic.drop(columns_to_drop, axis=1, errors='ignore', inplace=True)

dfBasic

,ShiftLength,CorsiForRelES,GFPer60,GAPer60,ATOIPP,PPCorsiPercRel,PPGFPer60,PPGAPer60,ATOISH,CorsiForRelSH,SHFPPer60,SHGAPer60,UID,season
0,0:29,-3.4,2.4,1.4,0:04,-37.2,14.3,0.0,0:03,15.1,0.0,0.0,greeraj01,22-23
1,0:45,1.5,3.1,3.8,3:17,1.1,9.8,1.0,2:47,-2.5,0.9,8.8,ekblaaa01,22-23
2,0:46,-2.5,1.2,0.6,0:27,19.8,0.0,0.0,0:00,NaN,NaN,NaN,ratyaa01,22-23
3,0:48,7.0,0.0,1.3,0:43,-5.2,0.0,0.0,0:00,NaN,NaN,NaN,beckmad01,22-23
4,0:41,4.6,3.2,3.9,3:03,-1.9,6.0,1.3,0:02,31.5,0.0,0.0,boqviad01,22-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946,0:44,-3.7,2.7,2.1,0:00,-20.9,0.0,0.0,1:22,-0.1,0.7,8.2,whiteza01,22-23
947,0:56,-10.6,2.1,2.6,0:53,-28.9,0.0,0.0,0:05,-16.4,0.0,0.0,jonesza01,22-23
948,0:39,-6.8,0.8,3.1,0:00,NaN,0.0,0.0,0:01,-8.2,0.0,60.0,kassiza01,22-23
949,0:44,-3.3,1.5,3.0,0:33,15.3,0.0,0.0,0:01,-9.5,NaN,NaN,macewza01,22-23
950,0:41,-0.4,1.7,2.0,0:03,-1.6,11.2,0.0,1:27,-4.3,0.0,8.7,girgeze01,22-23

In [5]:
# Construct the output file path
output_folder = "HockeyRef_Data_Files"
output_file_path = os.path.join(output_folder, f'{season_value}_TOIData.csv')

# Save the DataFrame to a CSV file with the constructed path
dfBasic.to_csv(output_file_path, index=False)